game_market/admin/users/routes.py
from flask import Blueprint, render_template, request, redirect, url_for, session, g
from game_market import db
from game_market.models import User

users = Blueprint('admin.users', __name__)

@users.before_request
def before_request():
    g.user = None
    if 'user' in session:
        g.user = session['user']

@users.route('/register', methods=['GET', 'POST'])
def register():
    if request.method == 'POST':
        user_data = {
            'name': request.form['name'],
            'email': request.form['email'],
            'username': request.form['username'],
            'password': request.form['password'],
            'is_admin': 1,
        }

        user = User(db, user_data)
        user.save()
        return redirect(url_for('users.login'))
    return render_template('admin/register.html')        
    
@users.route('/logout')
def logout():
    session.pop('user')
    return redirect(url_for('front_page.index'))
    

game_market/front_page/items/routes.py
from flask import Blueprint, render_template, redirect, url_for, g, session, request
from game_market import db
from game_market.models import Item, Cart

items = Blueprint('items', __name__)

@items.before_request
def before_request():
    g.user = None
    if 'user' in session:
        g.user = session['user']

@items.route('/view/<item>', methods=['GET'])
def view(item):
    item = Item(db).get(item)
    user = session['user'] if 'user' in session else None
    return render_template('front_page/items/view.html', 
        user=user, item=item)

@items.route('/pay/<item>', methods=['GET'])
def pay(item):
    Cart(db).pay(item)
    return redirect(url_for('users.account'))

@items.route('/delete/<item>', methods=['GET'])
def delete(item):
    Cart(db).delete(item)
    return redirect(url_for('users.account'))
 
@items.route('/add_to_cart/<item>', methods=['GET', 'POST'])
def add_to_cart(item):
    item = Item(db).add_to_cart(item, session['user']['id'])
    return redirect(url_for('users.account'))

game_market/front_page/routes.py
from flask import Blueprint, render_template, redirect, url_for, session
from game_market import db
from game_market.models import Item

front_page = Blueprint('front_page', __name__)

@front_page.route('/')
def index():
    items = Item(db).all_active()
    user = session['user'] if 'user' in session else None
    return render_template('front_page/index.html', items=items, user=user)

game_market/front_page/users/routes.py
from flask import Blueprint, render_template, redirect
from flask import url_for, g, session, request
from game_market import db
from game_market.models import User, Cart, TransactionHistory
users = Blueprint('users', __name__)

@users.before_request
def before_request():
    g.user = None
    if 'user' in session:
        g.user = session['user']

@users.route('/account')
def account():
    cart = Cart(db).get_user_all_unpaid_items(g.user['id'])
    bought_items = Cart(db).get_user_all_paid_items(g.user['id'])
    transaction_history = TransactionHistory(db).get_user_all(g.user['id'])
    
    if g.user == None:
        return redirect(url_for('front_page.index'))
    return render_template('front_page/users/index.html', 
        user=g.user, cart=cart, bought_items=bought_items,
        transaction_history=transaction_history)

@users.route('/login', methods=['GET', 'POST'])
def login():
    if request.method == 'POST':
        credentials = {
            'username': request.form['username'],
            'password': request.form['password']
        }

        user = User(db).login(credentials)

        if user:
            session['user'] = user
            g.user = user

    if g.user:
        if user['is_admin']:
            return redirect(url_for('admin.index'))
        return redirect(url_for('front_page.index'))
    return render_template('front_page/login.html')
 
@users.route('/register', methods=['GET', 'POST'])
def register():
    if request.method == 'POST':
        user_data = {
            'name': request.form['name'],
            'email': request.form['email'],
            'username': request.form['username'],
            'password': request.form['password'],
            'is_admin': 0,
        }

        user = User(db, user_data)
        user.save()
        return redirect(url_for('users.login'))

    return render_template('front_page/register.html')
 
@users.route('/transaction_history', methods=['GET'])
def transaction_history():
    history = User(db).get_history(session['user']['id'])
    return render_template('front_page/register.html',
        transaction_history=transaction_history,
        user=session['user'])

game_market/templates/front_page/users/index.html
{% extends 'front_page/master.html' %}

{% block stylesheets %}
<link href="{{ url_for('static', filename='vendors/dataTables/css/dataTables.min.css') }}" rel="stylesheet">
{% endblock stylesheets %}

{% block content %}
<div class="container mt-5">
    <div class="row">
        <div class="col-md-12">
            <div class="card mt-3">
                <div class="card-body">
                    <h3>Cart</h3>
                    <hr>
                    <table class="table">
                        <thead>
                            <th>Item</th>
                            <th>Price</th>
                            <th>Date</th>
                            <th>Action</th>
                        </thead>
                        <tbody>
                            {% for entry in cart %}
                            <tr>
                                <td>{{ entry['name'] }}</td>
                                <td>Php {{ entry['price'] }}</td>
                                <td>{{ entry['created_at'] }}</td>
                                <td>
                                    <a class="btn btn-sm btn-primary"
                                        href="{{ url_for('items.pay', item=entry['id']) }}">
                                        Pay
                                    </a>
                                    <a class="btn btn-sm btn-danger"
                                        href="{{ url_for('items.delete', item=entry['id']) }}">
                                        Delete
                                    </a>
                                </td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
            <div class="card mt-3">
                <div class="card-body">
                    <h3>Bought Items</h3>
                    <hr>
                    <table class="table">
                        <thead>
                            <th>Item</th>
                            <th>Price</th>
                            <th>Date</th>
                        </thead>
                        <tbody>
                            {% for entry in bought_items %}
                            <tr>
                                <td>{{ entry['name'] }}</td>
                                <td>Php {{ entry['price'] }}</td>
                                <td>{{ entry['created_at'] }}</td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
            <div class="card mt-3">
                <div class="card-body">
                    <h3>Transaction history</h3>
                    <hr>
                    <table class="table">
                        <thead>
                            <th>Action</th>
                            <th>Date</th>
                        </thead>
                        <tbody>
                            {% for entry in transaction_history %}
                            <tr>
                                <td>{{ entry['action'] }} {{ entry['name'] }} 
                                    {% if(entry['action'] == 'Added') %}
                                    to
                                    {% elif(entry['action'] == 'Removed') %}
                                    from
                                    {% endif %}
                                     cart</td>
                                <td>{{ entry['created_at'] }}</td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

{% block scripts %}
<script src="{{ url_for('static', filename='vendors/dataTables/js/dataTables.min.js') }}"></script>
<script>
$(function() {
    $('.table').DataTable()
})
</script>
{% endblock scripts %}