game_market/front_page/items/routes.py
from flask import Blueprint, render_template, redirect, url_for, g, session, request
from game_market import db
from game_market.models import Item, Cart

items = Blueprint('items', __name__)

@items.before_request
def before_request():
    g.user = None
    if 'user' in session:
        g.user = session['user']

@items.route('/view/<item>', methods=['GET'])
def view(item):
    item = Item(db).get(item)
    user = session['user'] if 'user' in session else None
    return render_template('front_page/items/view.html', 
        user=user, item=item)

@items.route('/pay/<item>', methods=['GET'])
def pay(item):
    Cart(db).pay(item)
    return redirect(url_for('users.account'))

@items.route('/delete/<item>', methods=['GET'])
def delete(item):
    Cart(db).delete(item)
    return redirect(url_for('users.account'))
 
@items.route('/add_to_cart/<item>', methods=['GET', 'POST'])
def add_to_cart(item):
    item = Item(db).add_to_cart(item, session['user']['id'])
    return redirect(url_for('users.account'))

game_market/front_page/routes.py
from flask import Blueprint, render_template, redirect, url_for, session
from game_market import db
from game_market.models import Item

front_page = Blueprint('front_page', __name__)

@front_page.route('/')
def index():
    items = Item(db).all_active()
    user = session['user'] if 'user' in session else None
    return render_template('front_page/index.html', items=items, user=user)

game_market/front_page/users/routes.py
from flask import Blueprint, render_template, redirect
from flask import url_for, g, session, request
from game_market import db
from game_market.models import User, Cart, TransactionHistory
users = Blueprint('users', __name__)

@users.before_request
def before_request():
    g.user = None
    if 'user' in session:
        g.user = session['user']

@users.route('/account')
def account():
    cart = Cart(db).get_user_all_unpaid_items(g.user['id'])
    bought_items = Cart(db).get_user_all_paid_items(g.user['id'])
    transaction_history = TransactionHistory(db).get_user_all(g.user['id'])
    
    if g.user == None:
        return redirect(url_for('front_page.index'))
    return render_template('front_page/users/index.html', 
        user=g.user, cart=cart, bought_items=bought_items,
        transaction_history=transaction_history)

@users.route('/login', methods=['GET', 'POST'])
def login():
    if request.method == 'POST':
        credentials = {
            'username': request.form['username'],
            'password': request.form['password']
        }

        user = User(db).login(credentials)

        if user:
            session['user'] = user
            g.user = user

    if g.user:
        if user['is_admin']:
            return redirect(url_for('admin.index'))
        return redirect(url_for('front_page.index'))
    return render_template('front_page/login.html')
 
@users.route('/register', methods=['GET', 'POST'])
def register():
    if request.method == 'POST':
        user_data = {
            'name': request.form['name'],
            'email': request.form['email'],
            'username': request.form['username'],
            'password': request.form['password'],
            'is_admin': 0,
        }

        user = User(db, user_data)
        user.save()
        return redirect(url_for('users.login'))

    return render_template('front_page/register.html')
 
@users.route('/transaction_history', methods=['GET'])
def transaction_history():
    history = User(db).get_history(session['user']['id'])
    return render_template('front_page/register.html',
        transaction_history=transaction_history,
        user=session['user'])

game_market/templates/front_page/index.html
{% extends 'front_page/master.html' %}

{% block jumbotron %}
<section class="jumbotron text-center">
    <div class="container">
        <h1 class="jumbotron-heading">Dota 2 Items</h1>
        <p class="lead text-muted">Something short and leading about the collection below—its contents, the creator, etc. Make it short and sweet, but not too short so folks don’t simply skip over it entirely.</p>
    </div>
</section>
{% endblock jumbotron %}

{% block content %}
<div class="album py-5 bg-light">
    <div class="container">

    <div class="row">

        {% if items|length < 1 %}
        <div class="col-md-12">
            <div class="div">
                <h3>No items yet in the market.</h3>
                <h4 class="lead">Please wait. Until further announcement regarding with the items. <br>Thank you for understanding.</h4>
            </div>
        </div>
        {% else %}
        {% for item in items %}
        <div class="col-md-4">
            <div class="card mb-4 shadow-sm">
                <img src="{{ url_for('static', filename='uploads/img/') }}/{{ item.img_path }}" alt="" 
                    class="card-img-top" width="100%" height="225" focusable="false" role="img" >
                <div class="card-body">
                <h5 class="card-title">{{ item.name }}</h5>
                <hr>
                <p class="card-text">
                    {{ item.description|truncate(150) }}
                </p>
                <div class="d-flex justify-content-between align-items-center">
                    <div class="btn-group">
                        <a class="btn btn-sm btn-outline-secondary"
                            href="{{ url_for('items.view', item=item.id) }}">View</a>
                        <button type="button" class="btn btn-sm btn-outline-secondary" 
                            {% if not user %}
                            data-toggle="modal" data-target="#loginErrorModal"
                            {% endif %}
                            >Add to cart</button>
                    </div>
                <small class="text-muted">Php {{ item.price }}</small>
                </div>
                </div>
            </div>
        </div>
        {% endfor %}
        {% endif %}
    </div>
</div>

<div class="modal fade" id="loginErrorModal" tabindex="-1" role="dialog" aria-labelledby="loginErrorModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="loginErrorModalLabel">You are not logged in.</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                Please login to add this item to cart.<br>
                If you don't have an account, click 
                <a href="{{ url_for('users.register') }}">here</a> to register.
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <a class="btn btn-primary" href="{{ url_for('users.login') }}">Login</a>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

game_market/templates/front_page/login.html
{% extends "admin/master-external.html" %}

{% block content %}
<div class="col-md-8">
  <div class="card-group">
    <div class="card p-4">
      <div class="card-body">
        <form action="{{ url_for('users.login') }}", method="POST">
          <h1>Login</h1>
          <p class="text-muted">Sign In to your account</p>
          <div class="input-group mb-3">
            <div class="input-group-prepend">
              <span class="input-group-text">
                <i class="icon-user"></i>
              </span>
            </div>
            <input type="username" name="username" id="username" 
              class="form-control" placeholder="Username">
          </div>
          <div class="input-group mb-4">
            <div class="input-group-prepend">
              <span class="input-group-text">
                <i class="icon-lock"></i>
              </span>
            </div>
            <input type="password" name="password" id="password" 
              class="form-control" placeholder="Password">
          </div>
          <div class="row">
            <div class="col-6">
              <button class="btn btn-primary px-4" type="submit">Login</button>
            </div>
            <div class="col-6 text-right">
              <button class="btn btn-link px-0" type="button">Forgot password?</button>
            </div>
          </div>
        </form>
      </div>
    </div>
    <div class="card text-white bg-primary py-5 d-md-down-none" style="width:44%">
      <div class="card-body text-center">
        <div>
          <h2>Sign up</h2>
          <p>You need to have an account to be able to access the page. <br>You can register by clicking the button below.</p>
          <a  href="{{ url_for('users.register') }}">
            <button class="btn btn-primary active mt-3" type="submit">Register Now!</button>
          </a>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock content %}

game_market/templates/front_page/master-external.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <base href="./">
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <meta name="description" content="CoreUI - Open Source Bootstrap Admin Template">
    <meta name="author" content="Łukasz Holeczek">
    <meta name="keyword" content="Bootstrap,Admin,Template,Open,Source,jQuery,CSS,HTML,RWD,Dashboard">
    <title>CoreUI Free Bootstrap Admin Template</title>
    <link href="{{ url_for('static', filename='vendors/@coreui/icons/css/coreui-icons.min.css') }}" rel="stylesheet">
    <link href="{{ url_for('static', filename='vendors/flag-icon-css/css/flag-icon.min.css') }}" rel="stylesheet">
    <link href="{{ url_for('static', filename='vendors/font-awesome/css/font-awesome.min.css') }}" rel="stylesheet">
    <link href="{{ url_for('static', filename='vendors/simple-line-icons/css/simple-line-icons.css') }}" rel="stylesheet">
    <link href="{{ url_for('static', filename='css/style.css') }}" rel="stylesheet">
    <link href="{{ url_for('static', filename='vendors/pace-progress/css/pace.min.css') }}" rel="stylesheet">
    {% block stylesheet %}
    {% endblock stylesheet %}
  </head>
  <body class="app flex-row align-items-center">
    <div class="container">
      <div class="row justify-content-center">
        <div class="col-md-8">
          {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
              {% for category, message in messages %}
              <div class="alert alert-{{category}}">
                {{ message }}
              </div>
              {% endfor %}
            {% endif %}
          {% endwith %}
        </div>
      </div>
      <div class="row justify-content-center">
        
        {% block content %}
        {% endblock content %}
      </div>
    </div>
    <!-- CoreUI and necessary plugins-->
    <script src="{{ url_for('static', filename='vendors/jquery/dist/jquery.min.js') }}"></script>
    <script src="{{ url_for('static', filename='vendors/popper.js/dist/umd/popper.min.js') }}"></script>
    <script src="{{ url_for('static', filename='vendors/bootstrap/dist/js/bootstrap.min.js') }}"></script>
    <script src="{{ url_for('static', filename='vendors/pace-progress/pace.min.js') }}"></script>
    <script src="{{ url_for('static', filename='vendors/perfect-scrollbar/dist/perfect-scrollbar.min.js') }}"></script>
    <script src="{{ url_for('static', filename='vendors/@coreui/coreui/dist/js/coreui.min.js') }}"></script>
    {% block javascript %}
    {% endblock javascript %}
  </body>
</html>

game_market/templates/front_page/master.html
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <meta name="description" content="">
        <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
        <meta name="generator" content="Jekyll v3.8.5">
        <title>Album example · Bootstrap</title>

        <link href="{{ url_for('static', filename='vendors/bootstrap/dist/css/bootstrap.min.css')}}" rel="stylesheet">
        <link href="{{ url_for('static', filename='vendors/font-awesome/css/font-awesome.min.css') }}" rel="stylesheet">
        <link href="{{ url_for('static', filename='vendors/simple-line-icons/css/simple-line-icons.css') }}" rel="stylesheet">
        {% block stylesheets %}
        {% endblock stylesheets %}
        <style>
            .bd-placeholder-img {
                font-size: 1.125rem;
                text-anchor: middle;
                -webkit-user-select: none;
                -moz-user-select: none;
                -ms-user-select: none;
                user-select: none;
            }

            @media (min-width: 768px) {
                .bd-placeholder-img-lg {
                    font-size: 3.5rem;
                }
            }
        </style>
        <link href="{{ url_for('static', filename='vendors/bootstrap/dist/album.css') }}" rel="stylesheet">
    </head>
    <body>
        <header>
            <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
                <div class="container">
                    <a class="navbar-brand" href="{{ url_for('front_page.index') }}"><strong>Game</strong>Market</a>
                    <div class="justify-contents">
                        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
                            <span class="navbar-toggler-icon"></span>
                        </button>
                        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                            <div class="navbar-nav">
                                {% if user == None %}
                                <a class="nav-item nav-link" href="{{ url_for('users.login') }}">Login</a>
                                <a class="nav-item nav-link" href="{{ url_for('users.register') }}">Register</a>
                                {% else %}
                                <a class="nav-item nav-link text-light" href="{{ url_for('users.account') }}"><strong>{{ user.name }}</strong></a>
                                <a class="nav-item nav-link text-light" href="{{ url_for('admin.users.logout') }}">Logout</a>
                                {% endif %}
                            </div>
                        </div>
                    </div>
                </div>
            </nav>
        </header>
        <main role="main">
            {% block jumbotron %} 
            {% endblock jumbotron %}

            {% block content %}
            {% endblock content %}
        </main>
        <script src="{{ url_for('static', filename='vendors/jquery/dist/jquery.min.js') }}"></script>
        <script src="{{ url_for('static', filename='vendors/popper.js/dist/umd/popper.min.js') }}"></script>
        <script src="{{ url_for('static', filename='vendors/bootstrap/dist/js/bootstrap.min.js') }}"></script>
        {% block scripts %}
        {% endblock scripts %}
    </body>
</html>

game_market/templates/front_page/register.html
{% extends "admin/master-external.html" %}

{% block content %}
<div class="col-md-6">
  <div class="card mx-4">
    <div class="card-body p-4">
      <form action="{{ url_for('users.register') }}" method="POST">
        <h1>Register</h1>
        <p class="text-muted">Create your account</p>
        <div class="input-group mb-3">
          <div class="input-group-prepend">
            <span class="input-group-text">
              <i class="icon-user"></i>
            </span>
          </div>
          <input type="text" name="username" id="username" 
            class="form-control" placeholder="Username">
        </div>
        <div class="input-group mb-3">
          <div class="input-group-prepend">
            <span class="input-group-text">@</span>
          </div>
          <input type="email" name="email" id="email" 
            class="form-control" placeholder="Email">
        </div>
        <div class="input-group mb-3">
          <div class="input-group-prepend">
            <span class="input-group-text">
              <i class="icon-user"></i>
            </span>
          </div>
          <input type="text" name="name" id="name" 
            class="form-control" placeholder="Name">
        </div>
        <div class="input-group mb-3">
          <div class="input-group-prepend">
            <span class="input-group-text">
              <i class="icon-lock"></i>
            </span>
          </div>
          <input type="password" name="password" id="password" 
            class="form-control" placeholder="Password">
        </div>
        <div class="input-group mb-4">
          <div class="input-group-prepend">
            <span class="input-group-text">
              <i class="icon-lock"></i>
            </span>
          </div>
          <input type="password" name="confirm_password" id="confirm_password" 
            class="form-control" placeholder="Confirm Password">
        </div>
        <button class="btn btn-block btn-success" type="submit">Create Account</button>
      </form>
    </div>
    <div class="card-footer p-4">
      <div class="row">
        <div class="col-12">
          <p>Login <a href="{{ url_for('users.login') }}">here.</a> If you already have an account.</p>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock content %}