game_market/admin/items/routes.py
from flask import Blueprint, render_template, request, redirect, url_for, session, g
from game_market import db, ROOT_DIR
from game_market.models import Item
import os
import datetime
import random

items = Blueprint('admin.items', __name__)

@items.before_request
def before_request():
    g.user = None
    if 'user' in session:
        g.user = session['user']

@items.route('/')
def index():
    if g.user:
        items = Item(db).all()
        return render_template('admin/items/index.html', items=items)
    return redirect(url_for('users.login'))

@items.route('/create')
def create():
    return render_template('admin/items/create.html')
    
@items.route('/save', methods=['POST'])
def save():
    
    img_path = ''
    image = None

    if('image' in request.files):
        image = request.files['image']
        img_path = image.filename
    
    relative_path = os.path.join('static', 'uploads', 'img')
    path_target = os.path.join(ROOT_DIR, relative_path)

    if img_path != '' and image != None:
        img_path = convert_filename(img_path)
        save_img_path = os.path.join(path_target, img_path)
        image.save(save_img_path)

    item_data = {
        'name': request.form['name'],
        'description': request.form['description'],
        'price': request.form['price'],
        'img_path': img_path
    } 

    item = Item(db, item_data)
    item.save()

    return redirect(url_for('admin.items.index'))

@items.route('/edit/<item>')
def edit(item):
    item = Item(db).get(item)
    return render_template('admin/items/edit.html', item=item)

@items.route('/update', methods=['POST'])
def update():
    item_data = {
        'id': request.form['id'],
        'name': request.form['name'],
        'description': request.form['description'],
        'price': request.form['price'],
    }
    item = Item(db).update(item_data)
    return redirect(url_for('admin.items.view', item=item_data['id']))

@items.route('/view/<item>')
def view(item):
    item = Item(db).get(item)
    history = Item(db).get_history(item['id'])
    return render_template('admin/items/view.html', item=item, history=history)

@items.route('/delete/<item>')
def delete(item):
    Item(db).delete(item)
    return redirect(url_for('admin.items.index'))

def convert_filename(filename):
    random_num = random.randint(0, 501)
    ext = os.path.splitext(filename)[1]
    date = datetime.datetime.now().strftime('%Y%m%d%H%M%S')
    return "%s-%s%s"%(random_num, date, ext)

game_market/front_page/items/routes.py
from flask import Blueprint, render_template, redirect, url_for, g, session, request
from game_market import db
from game_market.models import Item, Cart

items = Blueprint('items', __name__)

@items.before_request
def before_request():
    g.user = None
    if 'user' in session:
        g.user = session['user']

@items.route('/view/<item>', methods=['GET'])
def view(item):
    item = Item(db).get(item)
    user = session['user'] if 'user' in session else None
    return render_template('front_page/items/view.html', 
        user=user, item=item)

@items.route('/pay/<item>', methods=['GET'])
def pay(item):
    Cart(db).pay(item)
    return redirect(url_for('users.account'))

@items.route('/delete/<item>', methods=['GET'])
def delete(item):
    Cart(db).delete(item)
    return redirect(url_for('users.account'))
 
@items.route('/add_to_cart/<item>', methods=['GET', 'POST'])
def add_to_cart(item):
    item = Item(db).add_to_cart(item, session['user']['id'])
    return redirect(url_for('users.account'))

game_market/front_page/routes.py
from flask import Blueprint, render_template, redirect, url_for, session
from game_market import db
from game_market.models import Item

front_page = Blueprint('front_page', __name__)

@front_page.route('/')
def index():
    items = Item(db).all_active()
    user = session['user'] if 'user' in session else None
    return render_template('front_page/index.html', items=items, user=user)

game_market/front_page/users/routes.py
from flask import Blueprint, render_template, redirect
from flask import url_for, g, session, request
from game_market import db
from game_market.models import User, Cart, TransactionHistory
users = Blueprint('users', __name__)

@users.before_request
def before_request():
    g.user = None
    if 'user' in session:
        g.user = session['user']

@users.route('/account')
def account():
    cart = Cart(db).get_user_all_unpaid_items(g.user['id'])
    bought_items = Cart(db).get_user_all_paid_items(g.user['id'])
    transaction_history = TransactionHistory(db).get_user_all(g.user['id'])
    
    if g.user == None:
        return redirect(url_for('front_page.index'))
    return render_template('front_page/users/index.html', 
        user=g.user, cart=cart, bought_items=bought_items,
        transaction_history=transaction_history)

@users.route('/login', methods=['GET', 'POST'])
def login():
    if request.method == 'POST':
        credentials = {
            'username': request.form['username'],
            'password': request.form['password']
        }

        user = User(db).login(credentials)

        if user:
            session['user'] = user
            g.user = user

    if g.user:
        if user['is_admin']:
            return redirect(url_for('admin.index'))
        return redirect(url_for('front_page.index'))
    return render_template('front_page/login.html')
 
@users.route('/register', methods=['GET', 'POST'])
def register():
    if request.method == 'POST':
        user_data = {
            'name': request.form['name'],
            'email': request.form['email'],
            'username': request.form['username'],
            'password': request.form['password'],
            'is_admin': 0,
        }

        user = User(db, user_data)
        user.save()
        return redirect(url_for('users.login'))

    return render_template('front_page/register.html')
 
@users.route('/transaction_history', methods=['GET'])
def transaction_history():
    history = User(db).get_history(session['user']['id'])
    return render_template('front_page/register.html',
        transaction_history=transaction_history,
        user=session['user'])

game_market/templates/front_page/items/view.html
{% extends 'front_page/master.html' %}

{% block content %}
<div class="container">


<div class="card">
    <div class="card-body">
        <div class="row">
            <div class="col-md-4">
                <img src="{{ url_for('static', filename='uploads/img/') }}/{{ item.img_path }}" 
                    class="img-fluid" height="225" focusable="false" role="img" style="padding-bottom: 250px;">
            </div>
            <div class="col-md-8">
                <h2 class="card-title">{{ item.name }}</h2>
                <h6 class="text-primary">Php {{ item.price }}</h6>
                <hr>
                <p class="card-text">
                    {{ item.description }}
                </p>
                <hr>
                {% if user %}
                <a href="{{ url_for('items.add_to_cart', item=item.id) }}" 
                    class="btn btn-primary">Add to cart</a>
                {% else %}
                <button class="btn btn-primary" data-toggle="modal" 
                    data-target="#loginErrorModal">Add to cart</button>
                {% endif %}
                </button>
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="loginErrorModal" tabindex="-1" role="dialog" aria-labelledby="loginErrorModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="loginErrorModalLabel">You are not logged in.</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                Please login to add this item to cart.<br>
                If you don't have an account, click 
                <a href="{{ url_for('users.register') }}">here</a> to register.
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <a class="btn btn-primary" href="{{ url_for('users.login') }}">Login</a>
            </div>
        </div>
    </div>
</div>
{% endblock content %}